easy_admin:
    entities:
#        # List the entity class name you want to manage
        - App\Entity\Offer
        - App\Entity\Company
        - App\Entity\Industry
        - App\Entity\OfferType
